<?php
/**
 * Contacts — the bar's channels and the people who answer for the vacancies.
 *
 * Bar Settings → «Контакты» (acf-json/group_sp_contacts.json, generated by
 * tools/page-field-groups.py): phone, email, Telegram, VK, Instagram — one source for every
 * page. Until the tab is saved, data/contacts.php stands in, so nothing goes blank.
 * First consumer: the vacancy page (inc/vacancies.php, 25 Sep 2026). The Visit card, the
 * home Contacts section and the footer still type the same values — they move here next.
 *
 * The hiring contacts are a list on the same tab — name ⇄, role ⇄, phone, Telegram, email —
 * each row with a stable id issued on save (as the About quotes and the dish rows), so a
 * vacancy can point at a person and survive the list being reordered. A row that is gone
 * simply drops its vacancies back to the bar's channels.
 *
 * @package Sweet_Pepper
 */

/**
 * Digits and a leading plus — what a tel: link takes. '' when nothing is left.
 */
function sweet_pepper_tel( $phone ) {
    $tel = preg_replace( '/[^\d+]/', '', (string) $phone );
    return preg_match( '/\d{5,}/', $tel ) ? $tel : '';
}

/**
 * A Telegram handle as typed — "@name", "name" or "https://t.me/name" — as [ label, url ];
 * [ '', '' ] when empty.
 */
function sweet_pepper_telegram( $value ) {
    $value = trim( (string) $value );
    if ( '' === $value ) {
        return [ '', '' ];
    }
    if ( preg_match( '#^(?:https?://)?(?:t\.me|telegram\.me)/([A-Za-z0-9_]+)/?$#i', $value, $m ) ) {
        $value = $m[1];
    }
    $name = ltrim( $value, '@' );
    if ( ! preg_match( '/^[A-Za-z0-9_]{3,}$/', $name ) ) {
        return [ $value, '' ]; // typed something else — print it, link nothing
    }
    return [ '@' . $name, 'https://t.me/' . $name ];
}

/**
 * A social URL's handle for the row's text: "vk.com/sweetpepperbar", "@barsweetpepper".
 */
function sweet_pepper_social_label( $url, $network ) {
    $path = trim( (string) parse_url( (string) $url, PHP_URL_PATH ), '/' );
    if ( '' === $path ) {
        return '';
    }
    return 'instagram' === $network ? '@' . $path : 'vk.com/' . $path;
}

/**
 * The bar's channels, ready to print: each one '' when not set.
 *
 * @return array{phone:string, tel:string, email:string, telegram:string, telegram_url:string,
 *               vk:string, vk_label:string, instagram:string, instagram_label:string}
 */
function sweet_pepper_bar_contacts() {
    static $contacts = null;
    if ( null !== $contacts ) {
        return $contacts;
    }
    $typed = require get_template_directory() . '/data/contacts.php';
    $saved = function_exists( 'get_field' ) && '' !== trim( (string) get_field( 'contacts_phone', 'option' ) . get_field( 'contacts_email', 'option' ) );
    $get   = fn( $key ) => trim( (string) ( $saved ? get_field( "contacts_{$key}", 'option' ) : $typed[ $key ] ) );

    [ $tg, $tg_url ] = sweet_pepper_telegram( $get( 'telegram' ) );
    $contacts = [
        'phone'           => $get( 'phone' ),
        'tel'             => sweet_pepper_tel( $get( 'phone' ) ),
        'email'           => $get( 'email' ),
        'telegram'        => $tg,
        'telegram_url'    => $tg_url,
        'vk'              => $get( 'vk' ),
        'vk_label'        => sweet_pepper_social_label( $get( 'vk' ), 'vk' ),
        'instagram'       => $get( 'instagram' ),
        'instagram_label' => sweet_pepper_social_label( $get( 'instagram' ), 'instagram' ),
    ];
    return $contacts;
}

/**
 * The hiring contacts, keyed by their stable id, in the request's language.
 *
 * @return array<string, array{id:string, name:string, role:string, phone:string, tel:string,
 *                             telegram:string, telegram_url:string, email:string}>
 */
function sweet_pepper_hiring_contacts() {
    static $people = null;
    if ( null !== $people ) {
        return $people;
    }
    $people = [];
    if ( ! function_exists( 'get_field' ) ) {
        return $people;
    }
    foreach ( (array) get_field( 'hiring_contacts', 'option' ) as $i => $row ) {
        $id   = (string) ( $row['id'] ?? '' ) ?: 'p' . ( $i + 1 );
        $name = sweet_pepper_pick( $row, 'name' );
        if ( '' === $name ) {
            continue;
        }
        [ $tg, $tg_url ] = sweet_pepper_telegram( $row['telegram'] ?? '' );
        $people[ $id ] = [
            'id'           => $id,
            'name'         => $name,
            'role'         => sweet_pepper_pick( $row, 'role' ),
            'phone'        => trim( (string) ( $row['phone'] ?? '' ) ),
            'tel'          => sweet_pepper_tel( $row['phone'] ?? '' ),
            'telegram'     => $tg,
            'telegram_url' => $tg_url,
            'email'        => trim( (string) ( $row['email'] ?? '' ) ),
        ];
    }
    return $people;
}

/**
 * Every hiring contact gets a stable id on save, like the About quotes.
 */
add_action( 'acf/save_post', function ( $post_id ) {
    if ( 'options' !== $post_id ) {
        return;
    }
    $seen = [];
    foreach ( (array) get_field( 'hiring_contacts', 'option' ) as $i => $row ) {
        $id = $row['id'] ?? '';
        if ( '' === $id || isset( $seen[ $id ] ) ) {
            $id = 'p-' . bin2hex( random_bytes( 3 ) );
            update_sub_field( [ 'hiring_contacts', $i + 1, 'id' ], $id, 'option' );
        }
        $seen[ $id ] = true;
    }
}, 20 );
