<?php
/**
 * The two menu pages — «Меню» (the kitchen, /menu/) and «Меню — бар» (/menu/bar/) — and
 * what each page holds of its own (website-brief.md → Content editing → *Menu page fields*).
 *
 * Two pages, not one page with a query string (author, 24 Sep 2026): a page cache never
 * caches `?menu=drinks`, and each page gets its own title, canonical, hreflang, revisions
 * and edit lock. The STATE is the template — page-menu.php is the kitchen, page-menu-bar.php
 * the bar — so no editor can flip a page by accident. The old `/menu/?menu=drinks` is a
 * 301 to the bar page once that page exists (the hash survives a redirect); until then the
 * kitchen template still renders the bar for it, so a site whose bar page is not yet
 * created never breaks.
 *
 * Fields (acf-json/group_sp_menu.json, generated by tools/page-field-groups.py; one
 * group on both templates): the door to the other menu, the Highlights header and its
 * Relationship list of dishes, the browser title. Typed fallback and seed source:
 * data/menu/page.php. Section words are the section's (inc/menu-sections.php), dish
 * words the dish's (inc/menu-data-dishes.php) — a page never copies either.
 *
 * @package Sweet_Pepper
 */

/** state => page template. */
function sweet_pepper_menu_templates() {
    return [ 'food' => 'page-menu.php', 'drinks' => 'page-menu-bar.php' ];
}

/**
 * The page of a menu state, or null while it has not been created (page-seed.php menu makes
 * the bar page). Found by its template, not its slug, so the team may rename the page.
 *
 * @param string $state 'food' | 'drinks'
 * @return WP_Post|null
 */
function sweet_pepper_menu_page( $state ) {
    static $pages = [];
    if ( array_key_exists( $state, $pages ) ) {
        return $pages[ $state ];
    }
    $found = get_posts( [
        'post_type'   => 'page',
        'post_status' => 'publish',
        'numberposts' => 1,
        'orderby'     => 'ID',
        'order'       => 'ASC',
        'meta_key'    => '_wp_page_template',
        'meta_value'  => sweet_pepper_menu_templates()[ $state ] ?? '',
    ] );
    return $pages[ $state ] = $found[0] ?? null;
}

/**
 * The menu state of the current request: 'food' | 'drinks', '' off the menu pages.
 * The template decides; the kitchen page answers 'drinks' for `?menu=drinks` only while
 * no bar page exists (see the header).
 */
function sweet_pepper_menu_state() {
    if ( ! is_page() ) {
        return '';
    }
    $template = get_page_template_slug( get_queried_object_id() );
    $state    = array_search( $template, sweet_pepper_menu_templates(), true );
    if ( 'food' === $state && isset( $_GET['menu'] ) && 'drinks' === $_GET['menu'] && ! sweet_pepper_menu_page( 'drinks' ) ) { // phpcs:ignore WordPress.Security.NonceVerification -- a view switch
        return 'drinks';
    }
    return $state ?: '';
}

/**
 * A menu page's URL in the request's language, with a section anchor if asked:
 * `/menu/`, `/en/menu/bar/#cocktails`. get_permalink() carries the `/en/` prefix
 * (inc/lang.php → home_url filter). Without a bar page yet, the bar is the kitchen
 * page's `?menu=drinks`.
 *
 * @param string $state   'food' | 'drinks'
 * @param string $section Section slug, or ''.
 */
function sweet_pepper_menu_url( $state, $section = '' ) {
    $page = sweet_pepper_menu_page( $state );
    if ( $page ) {
        $url = get_permalink( $page );
    } elseif ( 'drinks' === $state ) {
        $url = home_url( '/menu/?menu=drinks' );
    } else {
        $url = home_url( '/menu/' );
    }
    return $url . ( $section ? '#' . $section : '' );
}

/**
 * `/menu/?menu=drinks` → `/menu/bar/` (301) once the bar page exists. Other query switches
 * (`?theme=`, `?daypart=`) are dropped with it: they were the checker's, not a guest's.
 */
function sweet_pepper_menu_legacy_redirect() {
    if ( 'food' !== sweet_pepper_menu_state() || ! isset( $_GET['menu'] ) || 'drinks' !== $_GET['menu'] || ! sweet_pepper_menu_page( 'drinks' ) ) { // phpcs:ignore WordPress.Security.NonceVerification -- a view switch
        return;
    }
    wp_safe_redirect( sweet_pepper_menu_url( 'drinks' ), 301 );
    exit;
}
add_action( 'template_redirect', 'sweet_pepper_menu_legacy_redirect' );

/**
 * A menu page's typed words (data/menu/page.php).
 */
function sweet_pepper_menu_page_typed( $state ) {
    static $typed = null;
    $typed ??= require get_template_directory() . '/data/menu/page.php';
    return $typed[ $state ] ?? $typed['food'];
}

/**
 * A page's prose field in the request's language, over the typed copy: the field, else
 * its twin, else the typed word in this language, else the English as typed.
 */
function sweet_pepper_menu_page_text( $state, $section, $key ) {
    $page  = sweet_pepper_menu_page( $state );
    $typed = sweet_pepper_menu_page_typed( $state )[ $section ] ?? [];
    return sp_field( "menu_{$section}_{$key}", sweet_pepper_typed( $typed, $key ), $page ? $page->ID : false );
}

/**
 * The hero's door on a menu page — the way to the OTHER menu: the word on the block and
 * the preview the hover opens (menu-hero.php, menu-hero.js). One language.
 *
 * @param string $state The page's state, 'food' | 'drinks'.
 * @return array [ slug, label, href, image (URL), focus, caption, description ]
 */
function sweet_pepper_menu_door( $state ) {
    $other = 'drinks' === $state ? 'food' : 'drinks';
    $page  = sweet_pepper_menu_page( $state );
    $typed = sweet_pepper_menu_page_typed( $state )['door'];
    $photo = $page && function_exists( 'get_field' ) ? get_field( 'menu_door_photo', $page->ID ) : '';
    return [
        'slug'        => $other,
        'label'       => sweet_pepper_menu_page_text( $state, 'door', 'label' ),
        'href'        => sweet_pepper_menu_url( $other ),
        'image'       => sweet_pepper_photo_url( $photo, 'sp-3x2', $typed['image'] ),
        'focus'       => $typed['focus'] ?? '50% 50%', // the tablet band's 21:9 crop of the preview (menu-hero.php); typed per photo
        'caption'     => sweet_pepper_menu_page_text( $state, 'door', 'caption' ),
        'description' => sweet_pepper_menu_page_text( $state, 'door', 'description' ),
    ];
}

/**
 * Every dish or drink of the menu in page order — the sections as the hero lists them,
 * each list's subsections in order, each list in order. What "the menu's order" means
 * for a strip that names no order of its own.
 *
 * @param string $state 'food' | 'drinks'
 * @return int[] Post IDs, published only, no repeats.
 */
function sweet_pepper_menu_items_in_order( $state ) {
    $ids = [];
    foreach ( array_keys( sweet_pepper_menu_sections_typed( $state ) ) as $slug ) {
        $list = get_page_by_path( $slug, OBJECT, 'menu_list' );
        if ( ! $list || ! function_exists( 'get_field' ) ) {
            continue;
        }
        foreach ( (array) get_field( 'menu_subsections', $list->ID ) as $sub ) {
            foreach ( (array) ( $sub['dishes'] ?? [] ) as $id ) {
                $ids[ (int) $id ] = true;
            }
        }
    }
    return array_values( array_filter( array_keys( $ids ), fn( $id ) => 'publish' === get_post_status( $id ) ) );
}

/**
 * A highlight card from a dish or drink post, in one language: name from the post, photo
 * = its featured image (3:2), else the photo of the section that places it — a card is
 * never blank; the link goes to that section, on this page as an anchor or on the other
 * menu page as a URL. Null for a post no list places (it is on no page to link to).
 *
 * @param int    $id    Dish or drink post.
 * @param string $state The page's state.
 * @return array|null Args of template-parts/components/menu-highlight-card.php, minus tilt.
 */
function sweet_pepper_menu_highlight_card( $id, $state ) {
    $post = get_post( $id );
    if ( ! $post || 'publish' !== $post->post_status || ! in_array( $post->post_type, sweet_pepper_menu_item_types(), true ) ) {
        return null;
    }
    $lists = sweet_pepper_dish_placements()[ $post->ID ] ?? [];
    $list  = $lists ? get_post( array_key_first( $lists ) ) : null;
    if ( ! $list ) {
        return null;
    }
    $slug    = $list->post_name;
    $section = sweet_pepper_menu_section( $slug );
    $home    = sweet_pepper_menu_state_for( $slug );
    $title   = sweet_pepper_pick( [ 'name_ru' => $post->post_title, 'name_en' => get_field( 'name_en', $post->ID ) ], 'name' );
    $typed   = sweet_pepper_menu_sections_typed( $home )[ $slug ] ?? [];
    return [
        'image_url' => sweet_pepper_photo_url( get_post_thumbnail_id( $post ), 'sp-3x2', $typed['image'] ?? '' ),
        'image_alt' => $title,
        'title'     => $title,
        'link_url'  => $home === $state ? '#' . $slug : sweet_pepper_menu_url( $home, $slug ),
    ] + sweet_pepper_menu_highlight_link_labels( $section );
}

/**
 * A card's link words for its section. English: "Show in Soups", "In Soups" on phones.
 * Russian (author, 23 Sep 2026): just the section's nav label — Супы · Салаты · Горячее —
 * not the headline: «Салаты от Перцев» overflows a 262px card; one label at every width.
 *
 * @param array $section A section of sweet_pepper_menu_sections(), in the request's language.
 * @return array [ link_label, link_label_mobile ]
 */
function sweet_pepper_menu_highlight_link_labels( $section ) {
    $label = $section['label'] ?? '';
    if ( 'ru' === sweet_pepper_lang() ) {
        return [ 'link_label' => $label, 'link_label_mobile' => '' ];
    }
    return [ 'link_label' => sprintf( 'Show in %s', $label ), 'link_label_mobile' => sprintf( 'In %s', $label ) ];
}

/**
 * The Highlights strip of a menu page: its header and its cards, one language.
 *
 * Cards, in order of what exists: the page's «Подборка» list → while that is empty, every
 * dish (or drink, on the bar page) of the menu that carries a seasonal label, in menu
 * order, eight at most → while the store has none, the typed cards. The strip never goes
 * blank; the two fallbacks are the reason the admin hint says what an empty list shows.
 *
 * @param string $state 'food' | 'drinks'
 * @return array [ eyebrow, headline, headline_2, cards => card args[] (tilt included), source => 'list'|'seasonal'|'typed' ]
 */
function sweet_pepper_menu_highlights( $state ) {
    $page   = sweet_pepper_menu_page( $state );
    $typed  = sweet_pepper_menu_page_typed( $state );
    $source = 'typed';
    $cards  = [];

    $ids = $page && function_exists( 'get_field' ) ? (array) get_field( 'menu_highlights', $page->ID, false ) : [];
    $ids = array_map( 'intval', array_filter( $ids ) );
    if ( $ids ) {
        $source = 'list';
    } elseif ( function_exists( 'get_field' ) ) {
        foreach ( sweet_pepper_menu_items_in_order( $state ) as $id ) {
            if ( '' !== trim( (string) get_field( 'seasonal_ru', $id ) . get_field( 'seasonal_en', $id ) ) ) {
                $ids[] = $id;
            }
        }
        $ids    = array_slice( $ids, 0, 8 );
        $source = $ids ? 'seasonal' : 'typed';
    }
    foreach ( $ids as $id ) {
        if ( $card = sweet_pepper_menu_highlight_card( $id, $state ) ) {
            $cards[] = $card;
        }
    }
    if ( ! $cards ) {
        $source = 'typed';
        foreach ( $typed['cards'] as $row ) {
            $slug    = $row['section'];
            $home    = sweet_pepper_menu_state_for( $slug );
            $title   = sweet_pepper_typed( $row, 'title' );
            $cards[] = [
                'image_url' => sweet_pepper_photo_url( '', 'sp-3x2', $row['image'] ),
                'image_alt' => $title,
                'title'     => $title,
                'link_url'  => $home === $state ? '#' . $slug : sweet_pepper_menu_url( $home, $slug ),
            ] + sweet_pepper_menu_highlight_link_labels( sweet_pepper_menu_section( $slug ) );
        }
    }
    foreach ( $cards as $i => &$card ) {
        $card['tilt'] = $i % 2 ? 'right' : 'left';
    }
    unset( $card );

    // Both headline lines from ONE language (inc/fields.php → sp_headline): the Russian heading
    // is one line, the English two — an empty line 2 must not borrow «Highlights».
    [ $headline, $headline_2 ] = sp_headline( 'menu_highlights_headline', $typed['highlights'], $page ? $page->ID : false );
    return [
        'eyebrow'    => sweet_pepper_menu_page_text( $state, 'highlights', 'eyebrow' ),
        'headline'   => $headline,
        'headline_2' => $headline_2,
        'cards'      => $cards,
        'source'     => $source,
    ];
}

// The «Подборка» picker shows size, price and the start of the description beside a name,
// as the section lists' picker does (inc/menu-data-dishes.php).
add_filter( 'acf/fields/relationship/result/key=field_sp_mpage_highlights', 'sweet_pepper_dish_relationship_result', 10, 2 );

/**
 * The browser tab: the page's «Поиск» title in the request's language stands in for the
 * page's WordPress title (one language); WordPress adds the site name as on every page.
 */
function sweet_pepper_menu_document_title( $parts ) {
    $state = sweet_pepper_menu_state();
    if ( $state ) {
        $title = sweet_pepper_menu_page_text( $state, 'seo', 'title' );
        if ( '' !== $title ) {
            $parts['title'] = $title;
        }
    }
    return $parts;
}
add_filter( 'document_title_parts', 'sweet_pepper_menu_document_title' );

/**
 * The description search engines show for a menu page.
 */
function sweet_pepper_menu_meta_description() {
    $state = sweet_pepper_menu_state();
    if ( ! $state ) {
        return;
    }
    $text = sweet_pepper_menu_page_text( $state, 'seo', 'description' );
    if ( '' !== $text ) {
        echo '<meta name="description" content="' . esc_attr( $text ) . '">' . "\n";
    }
}
add_action( 'wp_head', 'sweet_pepper_menu_meta_description', 1 );
