<?php
/**
 * Reserve drawer — the ready-made booking messages on its ticket (3 Oct 2026).
 *
 * Bar Settings → «Бронь — сообщения» (acf-json/group_sp_reserve_lines.json, generated by
 * tools/page-field-groups.py): a table of RU / EN twins with «Скрыть». Until it holds a line to
 * show, data/reserve-lines.php stands in, so the ticket is never empty. The drawer prints every
 * line; which one shows, and how a guest moves between them, is reserve-drawer.js →
 * initTicketLines (`?ticket=next|random`, on trial — website-brief.md → Reserve drawer).
 *
 * @package Sweet_Pepper
 */

/**
 * The lines in the request's language, in the team's order. A twin left empty borrows the
 * other language (sweet_pepper_pick), as the loader's pool does.
 *
 * @return string[]
 */
function sweet_pepper_reserve_lines() {
    $rows = function_exists( 'get_field' ) ? ( get_field( 'reserve_lines', 'option' ) ?: [] ) : [];
    $pick = function ( $rows ) {
        $lines = [];
        foreach ( (array) $rows as $row ) {
            $text = empty( $row['hidden'] ) ? sweet_pepper_pick( $row, 'line' ) : '';
            if ( '' !== $text ) {
                $lines[] = $text;
            }
        }
        return $lines;
    };
    return $pick( $rows ) ?: $pick( require get_template_directory() . '/data/reserve-lines.php' );
}
