<?php
/**
 * Vite asset enqueueing
 *
 * @package Sweet_Pepper
 */

define( 'IS_VITE_DEVELOPMENT', false ); // Set to true when running `npx vite` dev server

function sweet_pepper_vite_enqueue() {
    if ( IS_VITE_DEVELOPMENT ) {
        // Enqueue Vite client for HMR
        wp_enqueue_script( 'vite-client', 'http://localhost:5173/@vite/client', array(), null, false );
        
        // Enqueue main script as a module
        wp_enqueue_script( 'sweet-pepper-main', 'http://localhost:5173/src/main.js', array(), null, true );
    } else {
        // Production: read manifest.json generated by Vite
        $manifest_path = get_template_directory() . '/dist/.vite/manifest.json';
        
        if ( file_exists( $manifest_path ) ) {
            $manifest = json_decode( file_get_contents( $manifest_path ), true );
            
            if ( isset( $manifest['src/main.js'] ) ) {
                $js_file = $manifest['src/main.js']['file'];
                $css_file = isset( $manifest['src/main.js']['css'][0] ) ? $manifest['src/main.js']['css'][0] : '';
                
                wp_enqueue_script( 'sweet-pepper-main', get_template_directory_uri() . '/dist/' . $js_file, array(), SWEET_PEPPER_VERSION, true );
                
                if ( $css_file ) {
                    wp_enqueue_style( 'sweet-pepper-style', get_template_directory_uri() . '/dist/' . $css_file, array(), SWEET_PEPPER_VERSION );
                }
            }
        }
    }
}
add_action( 'wp_enqueue_scripts', 'sweet_pepper_vite_enqueue' );

// Add type="module" to vite scripts
function sweet_pepper_vite_module_type( $tag, $handle, $src ) {
    if ( in_array( $handle, array( 'vite-client', 'sweet-pepper-main' ), true ) ) {
        return '<script type="module" src="' . esc_url( $src ) . '"></script>';
    }
    return $tag;
}
add_filter( 'script_loader_tag', 'sweet_pepper_vite_module_type', 10, 3 );
