#!/usr/bin/env python3
"""Generate the menu field groups in sweet-pepper-theme/acf-json/.

The menu field groups are generated, not clicked (website-brief.md →
Content editing: "Field groups are generated"). Edit the fields here and re-run:

    python3 tools/menu-field-group.py

The menu store (website-brief.md → Menu storage, decided 23 Sep 2026 — option Б):
  group_sp_dish.json      — one dish or drink: on a `dish` post («Блюда») or a `drink` post («Напитки»)

The sections — their words, photos and subsections → ordered Relationship lists — live on the
two menu pages since 24 Sep 2026 (tools/page-field-groups.py → group_sp_menu_food / _bar; the
`menu_list` records of «Разделы меню» were migrated into them by tools/page-seed.php menu).

Keys are fixed (`field_sp_dish_*`), so re-running never orphans saved values. Field names are
read by sweet-pepper-theme/inc/menu-data.php, inc/menu-data-dishes.php and tools/menu-seed.php. The losing store's group (option А, a repeater of dish rows per section)
is in git at daf35b1; website-brief.md → Menu storage → *Option А, archived* describes it.
"""
from scf_fields import field, text, area, toggle, number, select, group, write_groups

# The theme holds the EN twin of each unit (inc/menu-data.php → sweet_pepper_menu_units()).
UNITS = {"g": "г", "ml": "мл", "l": "л", "pcs": "шт"}
# Values are file names in assets/icons/. Order here = order on the page.
# Legend (author, Sep 2026): leaf = vegetarian, fire = hit, pepper = spicy, Yaroslavl logo = local dish.
ICONS = {"veg": "Лист — вегетарианское", "fire": "Огонь — хит", "Pepper": "Перец — острое", "yaroslavl-logo": "Ярославль — местное блюдо"}

def dish_fields(prefix):
    """A dish's (or a drink's) own fields, in reading order — a post has a screen to itself.
    What a post has of its own is not here: the Russian name is its title, Draft takes it off
    the site, its post ID is the stable id."""
    f = lambda *a, **k: field(*a, prefix=prefix, **k)

    # The photo first (author, 24 Sep 2026: the featured-image box in the sidebar was not found).
    # inc/menu-data-dishes.php copies it into the post's featured image on save, so the pickers'
    # thumbnails and the seasonal strip read one thing.
    photo   = f("dish_photo", "Фото", "photo", "image", "",
                instructions="Горизонтальное фото 3:2 — на сайте обрезается по центру (сезонное меню, подборки).",
                return_format="id", library="all", min_width="", min_height="", min_size="", max_width="", max_height="",
                max_size="", mime_types="jpg,jpeg,png,webp", preview_size="medium")
    name_en = f("dish_name_en", "Название (EN)", "name_en", "text", "", **text)  # full width: the RU/EN pairs below stay paired
    # Size 1, and an optional size 2 (40 мл / 500 мл → 150 / 1300).
    sizes = [
        f("dish_amount", "Выход", "amount", "number", 14, **number),
        f("dish_unit", "Ед.", "unit", "select", 14, choices=UNITS, default_value="g", allow_null=0, **select),
        f("dish_price", "Цена", "price", "number", 22, **{**number, "append": "-."}),
        f("dish_amount_2", "Выход 2", "amount_2", "number", 14, **number),
        f("dish_unit_2", "Ед.", "unit_2", "select", 14, choices=UNITS, default_value="g", allow_null=0, **select),
        f("dish_price_2", "Цена 2", "price_2", "number", 22, **{**number, "append": "-."}),
    ]
    descriptions = [
        f("dish_description_ru", "Описание", "description_ru", "textarea", 50, **area),
        f("dish_description_en", "Описание (EN)", "description_en", "textarea", 50, **area),
    ]
    more = f("dish_more", "Дополнительно: значки, сезон, опции", "", "accordion", "", open=0, multi_expand=1, endpoint=0)
    extras = [
        f("dish_icons", "Значки — не больше двух", "icons", "checkbox", 50,
          choices=ICONS, default_value=[], return_format="value", allow_custom=0, save_custom=0,
          layout="horizontal", toggle=0),
        f("dish_highlight", "Выделить название", "highlight", "true_false", 50,
          **{**toggle, "message": "Хит, сезонное, фирменное"}),
        f("dish_seasonal_ru", "Сезонная метка", "seasonal_ru", "text", 50, **{**text, "placeholder": "Лето’26!"}),
        f("dish_seasonal_en", "Сезонная метка (EN)", "seasonal_en", "text", 50, **text),
        f("dish_options_ru", "Опции", "options_ru", "textarea", 50,
          instructions="Каждая опция с новой строки.", **{**area, "rows": 3}),
        # The note is repeated on the twin on purpose: a note on one side only leaves the pair uneven.
        f("dish_options_en", "Опции (EN)", "options_en", "textarea", 50,
          instructions="Каждая опция с новой строки.", **{**area, "rows": 3}),
    ]
    return [photo, name_en, *sizes, *descriptions, more, *extras]


# ── The menu store ──
D = "field_sp_dish_"
dish = group(
    "group_sp_dish", "Блюдо", dish_fields(D), ["dish", "drink"],
    "One dish or drink. Generated by tools/menu-field-group.py; read by inc/menu-data-dishes.php.")

write_groups((dish,))
